data<-data.frame(
  Name=c("A","B","c","D","E"),
  Age=c(20,21,NA,23,22),
  Marks=c(85,90,88,NA,76)
)
cat("Orginal Data:\n")
print(data)
cat("\nStructure:\n")
str(data)
cat("Summary\n")
summary(data)
cat("\nMissing Values:\n")
print(is.na(data))
cat("\nTotal Missing Values:\n")
print(sum(is.na(data)))
clean_data<-na.omit(data)
cat("\nData after removing NA:\n")
print(clean_data)
data$Age[is.na(data$Age)]<-mean(data$Age,na.rm=TRUE)
data$Marks[is.na(data$Marks)]<-mean(data$Marks,na.rm=TRUE)
cat("\nData after replaceing NA with mean:\n")
print(data)
cat("\nAverage Age:",mean(data$Age),"\n")
cat("\nAverage Marks:",mean(data$Marks),"\n")
cat("\nMax Marks:",max(data$Marks),"\n")
cat("\nMin Marks:",max(data$Marks),"\n" )